server:
  port: 8159
  servlet:
    context-path: /asc
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fixies;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /h2-console

# Call h2 console
# http://localhost:8159/asc/h2-console/


#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5439/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#    open-in-view: false


jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r
  lifetime: 36000000
